import type { ViewSchema } from "./types";

export const helpdeskTicketSchema: ViewSchema = {
  scope: "helpdesk.tickets",
  layouts: ["table"],
  fields: [
    { key: "subject", label: "Subject", type: "text", defaultVisible: true },
    { key: "reference_number", label: "Reference", type: "text", defaultVisible: true },
    {
      key: "status",
      label: "Status",
      type: "enum",
      defaultVisible: true,
      groupable: true,
      options: [
        { value: "new", label: "New" },
        { value: "open", label: "Open" },
        { value: "pending", label: "Pending" },
        { value: "on_hold", label: "On hold" },
        { value: "resolved", label: "Resolved" },
        { value: "closed", label: "Closed" },
        { value: "cancelled", label: "Cancelled" },
      ],
    },
    {
      key: "priority",
      label: "Priority",
      type: "enum",
      defaultVisible: true,
      groupable: true,
      options: [
        { value: "urgent", label: "Urgent" },
        { value: "high", label: "High" },
        { value: "medium", label: "Medium" },
        { value: "low", label: "Low" },
      ],
    },
    {
      key: "ticket_type",
      label: "Type",
      type: "enum",
      defaultVisible: true,
      groupable: true,
      options: [
        { value: "support", label: "Support" },
        { value: "incident", label: "Incident" },
        { value: "service_request", label: "Service Request" },
        { value: "question", label: "Question" },
        { value: "problem", label: "Problem" },
      ],
    },
    { key: "assignee_id", label: "Assignee", type: "user", defaultVisible: true, groupable: true },
    { key: "reporter_email", label: "Reporter", type: "text", defaultVisible: true },
    { key: "reporter_name", label: "Reporter name", type: "text" },
    { key: "queue_id", label: "Queue", type: "ref", groupable: true },
    {
      key: "channel",
      label: "Channel",
      type: "enum",
      options: [
        { value: "web", label: "Web" },
        { value: "email", label: "Email" },
        { value: "portal", label: "Portal" },
        { value: "api", label: "API" },
        { value: "phone", label: "Phone" },
      ],
    },
    {
      key: "sla_state",
      label: "SLA",
      type: "enum",
      options: [
        { value: "breached", label: "Breached" },
        { value: "at_risk", label: "At risk" },
        { value: "paused", label: "Paused" },
        { value: "on_track", label: "On track" },
        { value: "none", label: "No SLA" },
      ],
    },
    { key: "sla_breached", label: "SLA breached", type: "bool" },
    { key: "due_at", label: "Due", type: "date" },
    { key: "created_at", label: "Created", type: "date", defaultVisible: true },
    { key: "updated_at", label: "Updated", type: "date" },
    { key: "resolved_at", label: "Resolved", type: "date" },
    { key: "csat_score", label: "CSAT", type: "number" },
    { key: "tags", label: "Tags", type: "multiEnum" },
  ],
};
